### ISSUE TITLE
Why not ES6 modules?

### ISSUE THREAD

**Issue by jeremenichelli** [petehunt/react-webpack-template#6]
Is there a reason why you are using `require` instead of  `import` notation in **index.js**?

**Comment by petehunt** [comment]
* I don't use them and neither does Facebook. When FB ports its codebase to ES6 modules, I'll change my mind and port this over, but it's still early days for ES6 modules.
  * This repo is about getting React up and running with webpack. Adding es6 modules into the mix will probably just complicate things.
